import Head from "next/head";
// import ChatBox from "@upstash/chatbox";

import dynamic from "next/dynamic";

const ChatBox = dynamic(() => import("components/ChatBox/index"), {
  ssr: false,
});

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <ChatBox showOnInitial />
      </div>
    </div>
  );
}
